Repository scverse/scanpy, pull requests merged in 2021-02, with the labels that each got.

#1614 fixes dendrogram issue #1228
  docs/release-latest.rst
  scanpy/get/__init__.py
  scanpy/tests/_images/correlation.png
  scanpy/tests/_images/dendrogram.png
  scanpy/tests/_images/master_dotplot.png
  scanpy/tests/_images/master_dotplot3.png
  scanpy/tests/_images/master_dotplot_dict.png
  scanpy/tests/_images/master_dotplot_gene_symbols.png
  scanpy/tests/_images/master_dotplot_std_scale_group.png
  scanpy/tests/_images/master_dotplot_std_scale_var.png
  scanpy/tests/_images/master_heatmap_var_as_dict.png
  scanpy/tests/_images/master_matrixplot_std_scale_var_dict.png
  scanpy/tests/_images/master_multiple_plots.png
  scanpy/tests/_images/master_ranked_genes_dotplot.png
  scanpy/tests/_images/master_ranked_genes_dotplot_logfoldchange.png
  scanpy/tests/_images/master_ranked_genes_heatmap.png
  scanpy/tests/_images/master_ranked_genes_heatmap_swap_axes.png
  scanpy/tests/_images/master_ranked_genes_matrixplot.png
  scanpy/tests/_images/master_ranked_genes_matrixplot_swap_axes.png
  scanpy/tests/_images/master_ranked_genes_stacked_violin.png
  scanpy/tests/_images/master_ranked_genes_tracksplot.png
  scanpy/tests/_images/master_stacked_violin.png
  scanpy/tests/_images/master_stacked_violin_gene_symbols.png
  scanpy/tests/_images/master_stacked_violin_std_scale_var_dict.png
  scanpy/tests/_images/master_tsne.png
  scanpy/tools/_dendrogram.py
Labels: bug

#1628 Release notes reorganization
  docs/_links.rst
  docs/dev/documentation.rst
  docs/dev/release.rst
  docs/index.rst
  docs/release-notes.rst
  docs/release-notes/0.1.0.rst
  docs/release-notes/0.2.1.rst
  docs/release-notes/0.2.9.rst
  docs/release-notes/0.3.0.rst
  docs/release-notes/0.3.2.rst
  docs/release-notes/0.4.0.rst
  docs/release-notes/0.4.2.rst
  docs/release-notes/0.4.3.rst
  docs/release-notes/0.4.4.rst
  docs/release-notes/1.0.0.rst
  docs/release-notes/1.1.0.rst
  docs/release-notes/1.2.0.rst
  docs/release-notes/1.2.1.rst
  docs/release-notes/1.3.1.rst
  docs/release-notes/1.3.3.rst
  docs/release-notes/1.3.4.rst
  docs/release-notes/1.3.5.rst
  docs/release-notes/1.3.6.rst
  docs/release-notes/1.3.7.rst
  docs/release-notes/1.3.8.rst
  docs/release-notes/1.4.1.rst
  docs/release-notes/1.4.2.rst
  docs/release-notes/1.4.3.rst
  docs/release-notes/1.4.4.rst
  docs/release-notes/1.4.5.rst
  docs/release-notes/1.4.6.rst
  docs/release-notes/1.5.0.rst
  docs/release-notes/1.5.1.rst
  docs/release-notes/1.6.0.rst
  docs/release-notes/1.7.0.rst
  docs/release-notes/1.7.1.rst
  docs/release-notes/index.rst
  docs/release-notes/release-latest.rst
  docs/tutorials.rst
Labels: dev, docs

#1659 Fix passing of arguments between scrublet routines
  scanpy/external/pp/_scrublet.py
  scanpy/tests/external/test_scrublet.py
Labels: release-note needed
