Repository scverse/scanpy, pull requests merged in 2023-09, with the labels that each got.

#2658 Remove use of AnnData constructor dtype kwarg
  docs/release-notes/1.9.5.md
  scanpy/datasets/_datasets.py
  scanpy/testing/_helpers/__init__.py
  scanpy/tests/test_get.py
  scanpy/tests/test_highly_variable_genes.py
  scanpy/tests/test_normalization.py
  scanpy/tests/test_preprocessing.py
  scanpy/tests/test_scaling.py
Labels: Bug 🐛

#2660 Start 1.9.6
  docs/release-notes/1.9.5.md
  docs/release-notes/1.9.6.md
  docs/release-notes/index.md
Labels: Area - Documentation 📒, Development Process 🚀

#2664 Update Neighbors docstring
  scanpy/neighbors/__init__.py
Labels: Area - Documentation 📒

#2655 Harmony 64bit
  docs/release-notes/1.10.0.md
  scanpy/external/pp/_harmony_integrate.py
Labels: Area – External

#2646 Improve code samples in `neighbors` docs
  scanpy/neighbors/__init__.py
Labels: Area - Documentation 📒
