Repository scverse/scanpy, pull requests merged in 2023-08, with the labels that each got.

#2593 switch to pytestmark
  scanpy/tests/external/test_harmony_integrate.py
  scanpy/tests/external/test_harmony_timeseries.py
  scanpy/tests/external/test_magic.py
  scanpy/tests/external/test_sam.py
  scanpy/tests/external/test_scanorama_integrate.py
  scanpy/tests/external/test_scrublet.py
  scanpy/tests/test_normalization.py
  scanpy/tests/test_paga.py
  scanpy/tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#2596 Use faster default Python version for jobs
  .azure-pipelines.yml
  scanpy/cli.py
  scanpy/tests/test_binary.py
Labels: Development Process 🚀

#2594 1.9.4 release notes
  docs/release-notes/1.9.3.md
  docs/release-notes/1.9.4.md
Labels: Development Process 🚀, docs

#2597 Backport PR #2594 on branch 1.9.x (1.9.4 release notes)
  docs/release-notes/1.9.4.md
Labels: Development Process 🚀, docs

#2601 fixed `get.rank_genes_groups_df` with logreg
  docs/release-notes/1.9.4.md
  scanpy/get/get.py
Labels: Bug 🐛

#2606 Backport PR #2601 on branch 1.9.x (fixed `get.rank_genes_groups_df` with logreg)
  docs/release-notes/1.9.4.md
  scanpy/get/get.py
Labels: Bug 🐛

#2637 Improve n_jobs docs
  scanpy/_settings.py
Labels: Area - Documentation 📒

#2638 Backport PR #2637 on branch 1.9.x (Improve n_jobs docs)
  scanpy/_settings.py
Labels: Area - Documentation 📒

#2624 allow sc.pp.subsample in backed mode when returning a copy
  docs/release-notes/1.10.0.md
  scanpy/preprocessing/_simple.py
  scanpy/tests/test_preprocessing.py
Labels: Enhancement ✨
