Repository scverse/scanpy, pull requests merged in 2024-12, with the labels that each got.

#3393 (fix): bound sklearn because of dask-ml on the release candidate
  docs/release-notes/3393.bugfix.md
  pyproject.toml
Labels: Bug 🐛

#3394 Backport PR #3393 on branch 1.10.x ((fix): bound sklearn because of dask-ml on the release candidate)
  docs/release-notes/3393.bugfix.md
  pyproject.toml
Labels: Bug 🐛

#3396 Backport PR #3388: [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3367 Constrain all extras for min-deps job
  ci/scripts/min-deps.py
  hatch.toml
Labels: Development Process 🚀

#3399 Backport PR #3367 on branch 1.10.x (Constrain all extras for min-deps job)
  ci/scripts/min-deps.py
  hatch.toml
Labels: Development Process 🚀

#3403 Add a “improved documentation” category to enhancement template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Development Process 🚀

#3402 Modify error message if certifi is not installed
  src/scanpy/_compat.py
  src/scanpy/readwrite.py
Labels: Development Process 🚀

#3409 Scipy 1.15 compat, some test refactors
  src/scanpy/tools/_rank_genes_groups.py
  tests/test_backed.py
  tests/test_filter_rank_genes_groups.py
  tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#3412 (chore): generate 1.11.0 release notes
  ci/scripts/towncrier_automation.py
  docs/release-notes/1.11.0.md
  docs/release-notes/2921.feature.md
  docs/release-notes/3155.feature.md
  docs/release-notes/3180.feature.md
  docs/release-notes/3184.feature.md
  docs/release-notes/3263.feature.md
  docs/release-notes/3267.feature.md
  docs/release-notes/3284.performance.md
  docs/release-notes/3296.feature.md
  docs/release-notes/3307.feature.md
  docs/release-notes/3324.feature.md
  docs/release-notes/3335.feature.md
  docs/release-notes/3362.doc.md
  docs/release-notes/3380.bugfix.md
  docs/release-notes/3384.feature.md
  docs/release-notes/3393.bugfix.md
  docs/release-notes/3407.misc.md
  docs/release-notes/3410.feature.md
  docs/release-notes/943.feature.md
Labels: Development Process 🚀, no milestone
