Repository scverse/scanpy, pull requests merged in 2024-02, with the labels that each got.

#2838 Fix pytest 8 compat
  pyproject.toml
  scanpy/testing/_doctests.py
  scanpy/testing/_pytest/__init__.py
  scanpy/testing/_pytest/fixtures/__init__.py
  scanpy/tests/test_plotting.py
Labels: Development Process 🚀

#2843 Prevent oversubscription during tests
  scanpy/testing/_pytest/__init__.py
Labels: Development Process 🚀

#2845 Fix multithreading helper
  scanpy/testing/_pytest/__init__.py
Labels: Development Process 🚀

#2851 Add cell_ranger consistency test, fix test file extensions
  scanpy/tests/_scripts/cell_ranger_hvg.csv
  scanpy/tests/_scripts/seurat_extract_hvg.r
  scanpy/tests/_scripts/seurat_extract_hvg_v3.r
  scanpy/tests/_scripts/seurat_hvg.csv
  scanpy/tests/_scripts/seurat_hvg_v3.dat.gz
  scanpy/tests/_scripts/seurat_hvg_v3_batch.dat
  scanpy/tests/test_highly_variable_genes.py
  scanpy/tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#2855 Update log handling
  scanpy/logging.py
  scanpy/tests/conftest.py
  scanpy/tests/test_logging.py
Labels: Development Process 🚀

#2848 Turn on code cov patch annotations
  .codecov.yml
Labels: Development Process 🚀

#2816 Minimum dependency test job
  .azure-pipelines.yml
  ci/scripts/min-deps.py
  docs/release-notes/1.10.0.md
  pyproject.toml
  scanpy/get/get.py
  scanpy/neighbors/_backends/rapids.py
  scanpy/plotting/_baseplot_class.py
  scanpy/plotting/_matrixplot.py
  scanpy/plotting/_stacked_violin.py
  scanpy/plotting/_tools/scatterplots.py
  scanpy/preprocessing/_highly_variable_genes.py
  scanpy/preprocessing/_pca.py
  scanpy/testing/_helpers/__init__.py
  scanpy/testing/_pytest/__init__.py
  scanpy/testing/_pytest/params.py
  scanpy/tests/test_get.py
  scanpy/tests/test_metrics.py
  scanpy/tests/test_neighbors.py
  scanpy/tests/test_pca.py
  scanpy/tests/test_preprocessing.py
  scanpy/tests/test_preprocessing_distributed.py
  scanpy/tools/_dendrogram.py
Labels: Development Process 🚀

#2859 Convert string input on calculate qc metrics into collection for convenience
  docs/release-notes/1.10.0.md
  scanpy/preprocessing/_qc.py
  scanpy/tests/test_qc_metrics.py
Labels: Area – API, Area – Preprocessing 🧼

#2863 py 3.12 suport
  .azure-pipelines.yml
  .readthedocs.yml
  docs/release-notes/1.10.0.md
  pyproject.toml
Labels: Development Process 🚀

#2860 Improve image compare code
  scanpy/tests/conftest.py
Labels: Development Process 🚀

#2864 Fix pandas stack warning
  docs/release-notes/1.10.0.md
  scanpy/get/get.py
  scanpy/plotting/_stacked_violin.py
  scanpy/tests/test_pca.py
Labels: Bug 🐛

#2874 Fix coverage ci
  .azure-pipelines.yml
  pyproject.toml
  scanpy/preprocessing/_docs.py
  scanpy/tests/conftest.py
  scanpy/tests/test_aggregated.py
  scanpy/tests/test_pca.py
Labels: Bug 🐛, Development Process 🚀

#2872 re-order and rephrase some release notes
  docs/release-notes/1.10.0.md
Labels: Development Process 🚀

#2876 note that it's an rc
  docs/release-notes/1.10.0.md
Labels: Development Process 🚀

#2879 Fix pytest deprecation warning
  docs/release-notes/1.10.0.md
  scanpy/__init__.py
  scanpy/testing/_doctests.py
  scanpy/testing/_pytest/__init__.py
  scanpy/testing/_pytest/marks.py
Labels: Development Process 🚀

#2880 Backport PR #2879 on branch 1.10.x (Fix pytest deprecation warning)
  docs/release-notes/1.10.0.md
  scanpy/__init__.py
  scanpy/testing/_doctests.py
  scanpy/testing/_pytest/__init__.py
  scanpy/testing/_pytest/marks.py
Labels: Development Process 🚀

#2868 Allow blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: Development Process 🚀

#2882 Backport PR #2868 on branch 1.10.x (Allow blank issues)
  .github/ISSUE_TEMPLATE/config.yml
Labels: Development Process 🚀

#2883 Even more subtle blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: Development Process 🚀

#2877 start 0.11 release notes
  docs/release-notes/1.11.0.md
  docs/release-notes/index.md
Labels: Area - Documentation 📒, Development Process 🚀

#2886 Backport PR #2884 on branch 1.10.x (master-to-main)
  .azure-pipelines.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/check-pr.yml
  .pre-commit-config.yaml
  README.md
  docs/dev/code.md
  docs/dev/getting-set-up.md
  docs/dev/release.md
  docs/dev/testing.md
  docs/extensions/git_ref.py
  scanpy/tools/_rank_genes_groups.py
Labels: Development Process 🚀

#2890 Use index in score_genes
  scanpy/tests/test_score_genes.py
  scanpy/tools/_score_genes.py
Labels: Development Process 🚀

#2891 Backport PR #2890 on branch 1.10.x (Use index in score_genes)
  scanpy/tests/test_score_genes.py
  scanpy/tools/_score_genes.py
Labels: Development Process 🚀
