Repository scverse/scanpy, pull requests merged in 2024-06, with the labels that each got.

#3079 (fix): write out full PCA results when not run before neighbors
  docs/release-notes/1.10.2.md
  scanpy/tests/test_neighbors_key_added.py
  scanpy/tools/_utils.py
Labels: Area - Topology 🍩, Area - Dimensionality Reduction 🤏

#3082 Backport PR #3017 on branch 1.10.x (Hvg seurat v3 numba kernel)
  docs/release-notes/1.10.2.md
  scanpy/preprocessing/_highly_variable_genes.py
Labels: Area – Performance 🐌, benchmark

#3072 Backport PR #3048: (feat): raising errors where `backed` is not supported
  docs/release-notes/1.10.2.md
  scanpy/_utils/__init__.py
  scanpy/preprocessing/_pca.py
  scanpy/preprocessing/_scale.py
  scanpy/preprocessing/_simple.py
  scanpy/tests/test_backed.py
  scanpy/tests/test_ingest.py
  scanpy/tools/_dendrogram.py
  scanpy/tools/_ingest.py
  scanpy/tools/_rank_genes_groups.py
  scanpy/tools/_score_genes.py
  scanpy/tools/_tsne.py
  src/testing/scanpy/_pytest/fixtures/__init__.py
  src/testing/scanpy/_pytest/fixtures/data.py
Labels: Area - Documentation 📒, Area – API, Area - Out of core 💾

#3060 Document datasets
  .azure-pipelines.yml
  docs/extensions/patch_myst_nb.py
  docs/references.bib
  docs/release-notes/1.10.2.md
  scanpy/_utils/_doctests.py
  scanpy/datasets/_datasets.py
  scanpy/datasets/_ebi_expression_atlas.py
  scanpy/datasets/_utils.py
  scanpy/preprocessing/_deprecated/__init__.py
  scanpy/preprocessing/_deprecated/highly_variable_genes.py
  scanpy/tests/conftest.py
  scanpy/tests/test_datasets.py
  scanpy/tests/test_queries.py
  scanpy/tests/test_sim.py
  src/testing/scanpy/_pytest/__init__.py
  src/testing/scanpy/_pytest/marks.py
Labels: Area - Documentation 📒

#3094 Backport PR #3060 on branch 1.10.x (Document datasets)
  .azure-pipelines.yml
  docs/extensions/patch_myst_nb.py
  docs/references.bib
  docs/release-notes/1.10.2.md
  scanpy/_utils/_doctests.py
  scanpy/datasets/_datasets.py
  scanpy/datasets/_ebi_expression_atlas.py
  scanpy/datasets/_utils.py
  scanpy/preprocessing/_deprecated/__init__.py
  scanpy/preprocessing/_deprecated/highly_variable_genes.py
  scanpy/tests/conftest.py
  scanpy/tests/test_datasets.py
  scanpy/tests/test_queries.py
  scanpy/tests/test_sim.py
  src/testing/scanpy/_pytest/__init__.py
  src/testing/scanpy/_pytest/marks.py
Labels: Area - Documentation 📒

#3098 Backport PR #3097: Simplify score_genes
  scanpy/_utils/__init__.py
  scanpy/get/get.py
  scanpy/tests/test_score_genes.py
  scanpy/tools/_score_genes.py
Labels: Development Process 🚀

#3100 speedup(~7x) of the clipping array inside scaling function
  docs/release-notes/1.10.2.md
  src/scanpy/preprocessing/_scale.py
Labels: benchmark

#3112 Backport PR #3100: speedup(~7x) of the clipping array inside scaling function
  docs/release-notes/1.10.2.md
  src/scanpy/preprocessing/_scale.py
Labels: benchmark

#3125 Skip scanorama on Python 3.9
  tests/external/test_scanorama_integrate.py
Labels: Area – External, Development Process 🚀

#3126 Backport PR #3125: Skip scanorama on Python 3.9
  tests/external/test_scanorama_integrate.py
Labels: Area – External, Development Process 🚀
