Repository scverse/scanpy, pull requests merged in 2024-03, with the labels that each got.

#2903 tutorial link for `transformer`
  scanpy/neighbors/__init__.py
  scanpy/tests/test_score_genes.py
Labels: Area - Documentation 📒, Development Process 🚀

#2915 Backport PR #2905 on branch 1.10.x (Remove inplace modification of a buffer created by pandas)
  pyproject.toml
  scanpy/preprocessing/_highly_variable_genes.py
  scanpy/testing/_pytest/__init__.py
Labels: Bug 🐛, Upstream, Development Process 🚀

#2914 fixes pca_test `test_mask_defaults`
  scanpy/tests/test_pca.py
Labels: Development Process 🚀

#2904 Backport PR #2903 on branch 1.10.x (tutorial link for `transformer`)
  scanpy/neighbors/__init__.py
  scanpy/tests/test_score_genes.py
Labels: Area - Documentation 📒, Development Process 🚀

#2918 Backport PR #2914 on branch 1.10.x (fixes pca_test `test_mask_defaults`)
  scanpy/tests/test_pca.py
Labels: Development Process 🚀

#2919 Backport PR #2907 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  docs/extensions/function_images.py
  scanpy/__init__.py
  scanpy/_utils/__init__.py
  scanpy/_utils/compute/is_constant.py
  scanpy/datasets/__init__.py
  scanpy/experimental/_docs.py
  scanpy/external/exporting.py
  scanpy/external/pp/_harmony_integrate.py
  scanpy/external/pp/_hashsolo.py
  scanpy/external/pp/_magic.py
  scanpy/external/pp/_scanorama_integrate.py
  scanpy/external/tl/_harmony_timeseries.py
  scanpy/external/tl/_palantir.py
  scanpy/external/tl/_phate.py
  scanpy/external/tl/_phenograph.py
  scanpy/external/tl/_pypairs.py
  scanpy/external/tl/_sam.py
  scanpy/external/tl/_trimap.py
  scanpy/get/get.py
  scanpy/logging.py
  scanpy/metrics/_metrics.py
  scanpy/metrics/_morans_i.py
  scanpy/neighbors/_types.py
  scanpy/plotting/_anndata.py
  scanpy/plotting/_baseplot_class.py
  scanpy/plotting/_docs.py
  scanpy/plotting/_rcmod.py
  scanpy/plotting/palettes.py
  scanpy/preprocessing/_distributed.py
  scanpy/preprocessing/_docs.py
  scanpy/preprocessing/_recipes.py
  scanpy/preprocessing/_scrublet/__init__.py
  scanpy/preprocessing/_scrublet/core.py
  scanpy/preprocessing/_simple.py
  scanpy/readwrite.py
  scanpy/testing/_helpers/__init__.py
  scanpy/testing/_pytest/fixtures/__init__.py
  scanpy/tests/test_datasets.py
  scanpy/tests/test_pca.py
  scanpy/tools/_dpt.py
  scanpy/tools/_embedding_density.py
  scanpy/tools/_marker_gene_overlap.py
  scanpy/tools/_rank_genes_groups.py
  scanpy/tools/_score_genes.py
  scanpy/tools/_sim.py
  scanpy/tools/_top_genes.py
Labels: Development Process 🚀

#2920 Backport PR #2916 on branch 1.10.x (Run CI with uv)
  .azure-pipelines.yml
Labels: Development Process 🚀

#2922 Fixed Coifman 2005 DOI link.
  docs/references.rst
Labels: Area - Documentation 📒, Development Process 🚀

#2925 Backport PR #2922 on branch 1.10.x (Fixed Coifman 2005 DOI link.)
  docs/references.rst
Labels: Area - Documentation 📒, Development Process 🚀

#2943 Fix paga
  .azure-pipelines.yml
  docs/release-notes/1.10.0.md
  scanpy/_utils/__init__.py
  scanpy/tools/_paga.py
Labels: Bug 🐛

#2947 Backport PR #2856 on branch 1.10.x ((feat): pre-processing functions for `dask` with sparse chunks)
  docs/release-notes/1.10.0.md
  scanpy/_utils/__init__.py
  scanpy/preprocessing/_distributed.py
  scanpy/preprocessing/_highly_variable_genes.py
  scanpy/preprocessing/_normalization.py
  scanpy/preprocessing/_simple.py
  scanpy/preprocessing/_utils.py
  scanpy/testing/_pytest/params.py
  scanpy/tests/test_highly_variable_genes.py
  scanpy/tests/test_normalization.py
  scanpy/tests/test_pca.py
  scanpy/tests/test_preprocessing.py
  scanpy/tests/test_utils.py
Labels: Area – Performance 🐌, Area - Out of core 💾, Area – Preprocessing 🧼

#2944 Backport PR #2943 on branch 1.10.x (Fix paga)
  .azure-pipelines.yml
  docs/release-notes/1.10.0.md
  scanpy/_utils/__init__.py
  scanpy/tools/_paga.py
Labels: Bug 🐛

#2934 Fix aggregating obsm/ varm
  scanpy/get/_aggregated.py
  scanpy/tests/test_aggregated.py
Labels: Bug 🐛

#2948 Backport PR #2934 on branch 1.10.x (Fix aggregating obsm/ varm)
  scanpy/get/_aggregated.py
  scanpy/tests/test_aggregated.py
Labels: Bug 🐛

#2959 Backport PR #2953 on branch 1.10.x (Fix links)
  CONTRIBUTING.md
  README.md
  docs/index.md
  docs/installation.md
Labels: Area - Documentation 📒, Development Process 🚀

#2961 Backport PR #2960 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀
