Repository scverse/scanpy, pull requests merged in 2024-01, with the labels that each got.

#2805 Add rtd-sphinx-search
  docs/_static/css/override.css
  docs/conf.py
  docs/release-notes/1.10.0.md
  pyproject.toml
Labels: Area - Documentation 📒

#2810 Fix hvg warnings
  scanpy/experimental/pp/_highly_variable_genes.py
  scanpy/preprocessing/_highly_variable_genes.py
  scanpy/testing/_pytest/fixtures/data.py
  scanpy/tests/test_highly_variable_genes.py
Labels: Development Process 🚀

#2814 Test full Dask support for `log1p`, `normalize_per_cell`, `filter_cells`/`filter_genes`
  scanpy/_compat.py
  scanpy/preprocessing/_distributed.py
  scanpy/preprocessing/_simple.py
  scanpy/tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#2817 Use version helper everywhere
  scanpy/tests/test_embedding_plots.py
  scanpy/tests/test_rank_genes_groups.py
Labels: Development Process 🚀

#2831 Prepare 1.9.8, stop ignoring citation errors
  docs/conf.py
  docs/references.rst
  docs/release-notes/1.9.8.md
  docs/release-notes/index.md
Labels: Development Process 🚀

#2832 Fix for _validate_palette for old numpy versions, prepare 1.9.8 hotfix release
  docs/release-notes/1.9.8.md
  scanpy/plotting/_utils.py
Labels: Area - Plotting 🌺

#2834 Run ci on release branch
  .azure-pipelines.yml
Labels: Development Process 🚀

#2835 Backport PR #2834 on branch 1.9.x (Run ci on release branch)
  .azure-pipelines.yml
Labels: Development Process 🚀
