Repository scverse/scanpy, pull requests merged in 2024-05, with the labels that each got.

#3047 Fixes for sklearn 1.5
  docs/conf.py
  scanpy/_compat.py
  scanpy/_utils/__init__.py
  scanpy/datasets/_utils.py
  scanpy/external/pp/_magic.py
  scanpy/external/tl/_pypairs.py
  scanpy/preprocessing/_pca.py
  scanpy/preprocessing/_utils.py
  scanpy/testing/_pytest/fixtures/data.py
  scanpy/testing/_pytest/marks.py
  scanpy/tests/_images/binary_pca/expected.png
  scanpy/tests/_images/binary_pca_old/expected.png
  scanpy/tests/conftest.py
  scanpy/tests/test_normalization.py
  scanpy/tests/test_pca.py
  scanpy/tests/test_plotting.py
  scanpy/tests/test_preprocessing.py
  scanpy/tests/test_rank_genes_groups.py
  scanpy/tools/_ingest.py
  scanpy/tools/_louvain.py
  scanpy/tools/_tsne.py
Labels: Development Process 🚀

#3050 Backport PR #3047 on branch 1.10.x (Fixes for sklearn 1.5)
  docs/conf.py
  scanpy/_compat.py
  scanpy/_utils/__init__.py
  scanpy/datasets/_utils.py
  scanpy/external/pp/_magic.py
  scanpy/external/tl/_pypairs.py
  scanpy/preprocessing/_pca.py
  scanpy/preprocessing/_utils.py
  scanpy/testing/_pytest/fixtures/data.py
  scanpy/testing/_pytest/marks.py
  scanpy/tests/_images/binary_pca/expected.png
  scanpy/tests/_images/binary_pca_old/expected.png
  scanpy/tests/conftest.py
  scanpy/tests/test_normalization.py
  scanpy/tests/test_pca.py
  scanpy/tests/test_plotting.py
  scanpy/tests/test_preprocessing.py
  scanpy/tests/test_rank_genes_groups.py
  scanpy/tools/_ingest.py
  scanpy/tools/_louvain.py
  scanpy/tools/_tsne.py
Labels: Development Process 🚀

#3031 Extend benchmarks from basic tutorial
  benchmarks/asv.conf.json
  benchmarks/benchmarks/_utils.py
  benchmarks/benchmarks/preprocessing.py
  benchmarks/benchmarks/preprocessing_counts.py
  benchmarks/benchmarks/preprocessing_log.py
  benchmarks/benchmarks/tools.py
  benchmarks/benchmarks/utils.py
  scanpy/preprocessing/_highly_variable_genes.py
  scanpy/preprocessing/_scrublet/__init__.py
  scanpy/preprocessing/_scrublet/core.py
  scanpy/preprocessing/_simple.py
  scanpy/tests/test_scrublet.py
  scanpy/tools/_rank_genes_groups.py
Labels: Development Process 🚀, benchmark

#3056 Backport PR #3031 on branch 1.10.x (Extend benchmarks from basic tutorial)
  benchmarks/asv.conf.json
  benchmarks/benchmarks/_utils.py
  benchmarks/benchmarks/preprocessing.py
  benchmarks/benchmarks/preprocessing_counts.py
  benchmarks/benchmarks/preprocessing_log.py
  benchmarks/benchmarks/tools.py
  benchmarks/benchmarks/utils.py
  scanpy/preprocessing/_highly_variable_genes.py
  scanpy/preprocessing/_scrublet/__init__.py
  scanpy/preprocessing/_scrublet/core.py
  scanpy/preprocessing/_simple.py
  scanpy/tests/test_scrublet.py
  scanpy/tools/_rank_genes_groups.py
Labels: Development Process 🚀, benchmark

#3044 Speedup scrublet
  docs/release-notes/1.10.2.md
  scanpy/preprocessing/_scrublet/__init__.py
  scanpy/preprocessing/_scrublet/pipeline.py
  scanpy/preprocessing/_scrublet/sparse_utils.py
Labels: Area – Performance 🐌, benchmark

#3058 Backport PR #3044 on branch 1.10.x (Speedup scrublet)
  docs/release-notes/1.10.2.md
  scanpy/preprocessing/_scrublet/__init__.py
  scanpy/preprocessing/_scrublet/pipeline.py
  scanpy/preprocessing/_scrublet/sparse_utils.py
Labels: Area – Performance 🐌, benchmark

#3065 Upper-bound numpy below 2 for now
  pyproject.toml
  scanpy/experimental/_docs.py
  scanpy/plotting/_docs.py
  scanpy/plotting/_tools/__init__.py
  scanpy/tests/test_highly_variable_genes.py
  scanpy/tests/test_normalization.py
Labels: Development Process 🚀

#3066 Backport PR #3065 on branch 1.10.x (Upper-bound numpy below 2 for now)
  pyproject.toml
  scanpy/experimental/_docs.py
  scanpy/plotting/_docs.py
  scanpy/plotting/_tools/__init__.py
  scanpy/tests/test_highly_variable_genes.py
  scanpy/tests/test_normalization.py
Labels: Development Process 🚀

#3017 Hvg seurat v3 numba kernel
  docs/release-notes/1.10.2.md
  scanpy/preprocessing/_highly_variable_genes.py
Labels: Area – Performance 🐌, benchmark
