Repository scverse/scanpy, pull requests merged in 2024-07, with the labels that each got.

#3130 Backport PR #3119 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3145 Use version guards instead of “except ImportError”
  src/scanpy/_compat.py
  src/testing/scanpy/_helpers/data.py
Labels: Development Process 🚀

#3146 Backport PR #3145 on branch 1.10.x (Use version guards instead of “except ImportError”)
  src/scanpy/_compat.py
  src/testing/scanpy/_helpers/data.py
Labels: Development Process 🚀

#3151 Backport PR #3148: [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3161 Backport PR #3156: [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  docs/_templates/autosummary/class.rst
Labels: Development Process 🚀

#3147 Run benchmarks for off axis
  benchmarks/README.md
  benchmarks/asv.conf.json
  benchmarks/benchmarks/_utils.py
  benchmarks/benchmarks/preprocessing_counts.py
  benchmarks/benchmarks/preprocessing_log.py
Labels: Development Process 🚀, benchmark

#3165 Backport PR #3162 on branch 1.10.x (Fix tests for dask PCA)
  src/testing/scanpy/_helpers/__init__.py
  tests/test_highly_variable_genes.py
  tests/test_pca.py
  tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#3166 Backport PR #3147: Run benchmarks for off axis
  benchmarks/README.md
  benchmarks/asv.conf.json
  benchmarks/benchmarks/_utils.py
  benchmarks/benchmarks/preprocessing_counts.py
  benchmarks/benchmarks/preprocessing_log.py
Labels: Development Process 🚀, benchmark

#3170 Refactor score_genes
  src/scanpy/tools/_score_genes.py
  tests/test_score_genes.py
Labels: Development Process 🚀

#3172 Switch from using rubric in release notes
  docs/conf.py
  docs/ecosystem.md
  docs/index.md
  docs/news.md
  docs/release-notes/0.1.0.md
  docs/release-notes/0.2.1.md
  docs/release-notes/0.2.9.md
  docs/release-notes/0.3.0.md
  docs/release-notes/0.3.2.md
  docs/release-notes/0.4.0.md
  docs/release-notes/0.4.2.md
  docs/release-notes/0.4.3.md
  docs/release-notes/0.4.4.md
  docs/release-notes/1.0.0.md
  docs/release-notes/1.1.0.md
  docs/release-notes/1.10.0.md
  docs/release-notes/1.10.1.md
  docs/release-notes/1.10.2.md
  docs/release-notes/1.10.3.md
  docs/release-notes/1.11.0.md
  docs/release-notes/1.2.0.md
  docs/release-notes/1.2.1.md
  docs/release-notes/1.3.1.md
  docs/release-notes/1.3.3.md
  docs/release-notes/1.3.4.md
  docs/release-notes/1.3.5.md
  docs/release-notes/1.3.6.md
  docs/release-notes/1.3.7.md
  docs/release-notes/1.3.8.md
  docs/release-notes/1.4.1.md
  docs/release-notes/1.4.2.md
  docs/release-notes/1.4.3.md
  docs/release-notes/1.4.4.md
  docs/release-notes/1.4.5.md
  docs/release-notes/1.4.6.md
  docs/release-notes/1.5.0.md
  docs/release-notes/1.5.1.md
  docs/release-notes/1.6.0.md
  docs/release-notes/1.7.0.md
  docs/release-notes/1.7.1.md
  docs/release-notes/1.7.2.md
  docs/release-notes/1.8.0.md
  docs/release-notes/1.8.1.md
  docs/release-notes/1.8.2.md
  docs/release-notes/1.9.0.md
  docs/release-notes/1.9.1.md
  docs/release-notes/1.9.2.md
  docs/release-notes/1.9.3.md
  docs/release-notes/1.9.4.md
  docs/release-notes/1.9.5.md
  docs/release-notes/1.9.6.md
  docs/release-notes/1.9.7.md
  docs/release-notes/1.9.8.md
Labels: Area - Documentation 📒, Development Process 🚀

#3175 Backport PR #3174 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3177 Cache data for subsequent test runs
  src/testing/scanpy/_pytest/__init__.py
  src/testing/scanpy/_pytest/fixtures/__init__.py
  tests/test_datasets.py
Labels: Development Process 🚀

#3179 Backport PR #3177 on branch 1.10.x (Cache data for subsequent test runs)
  src/testing/scanpy/_pytest/__init__.py
  src/testing/scanpy/_pytest/fixtures/__init__.py
  tests/test_datasets.py
Labels: Development Process 🚀
