Repository scverse/scanpy, pull requests merged in 2024-10, with the labels that each got.

#3271 Backport PR #3270 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  src/scanpy/plotting/_anndata.py
Labels: Development Process 🚀

#3287 Fix #3206’s release note
  docs/release-notes/3206.bugfix.md
Labels: Development Process 🚀

#3288 Backport PR #3287 on branch 1.10.x (Fix #3206’s release note)
  docs/release-notes/3206.bugfix.md
Labels: Development Process 🚀

#3292 Fix benchmark job: Use upstream asv
  .github/workflows/benchmark.yml
Labels: Development Process 🚀

#3293 Backport PR #3292 on branch 1.10.x (Fix benchmark job: Use upstream asv)
  .github/workflows/benchmark.yml
Labels: Development Process 🚀

#3294 Test all PCA param combinations
  src/testing/scanpy/_pytest/params.py
  tests/test_pca.py
Labels: Development Process 🚀

#3304 Backport PR #3298 on branch 1.10.x ((fix): correct anndata release for `io` usage)
  src/scanpy/__init__.py
  src/scanpy/readwrite.py
  src/testing/scanpy/_pytest/fixtures/data.py
Labels: Bug 🐛

#3305 Backport PR #3274 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3306 (fix): clarify sparse pca usage
  docs/release-notes/3267.feature.md
  src/scanpy/preprocessing/_pca/__init__.py
  src/scanpy/preprocessing/_pca/_dask_sparse.py
  tests/test_pca.py
Labels: Area - Documentation 📒, Area - Out of core 💾

#3316 Refactor regress_out
  src/scanpy/preprocessing/_simple.py
Labels: Development Process 🚀

#3322 Backport PR #3316 on branch 1.10.x (Refactor regress_out)
  src/scanpy/preprocessing/_simple.py
Labels: Development Process 🚀

#3321 Enforce `np.bool_` usage via Ruff
  pyproject.toml
  src/scanpy/plotting/_anndata.py
Labels: Development Process 🚀

#3323 Backport PR #3321 on branch 1.10.x (Enforce `np.bool_` usage via Ruff)
  pyproject.toml
  src/scanpy/plotting/_anndata.py
Labels: Development Process 🚀

#3285 Update `test_rank_genes_groups.py` reference
  src/scanpy/tools/_rank_genes_groups.py
Labels: Development Process 🚀

#3327 Backport PR #3285 on branch 1.10.x (Update `test_rank_genes_groups.py` reference)
  src/scanpy/tools/_rank_genes_groups.py
Labels: Development Process 🚀
