Repository scverse/scanpy, pull requests merged in 2024-04, with the labels that each got.

#2972 Fix double dot
  docs/conf.py
Labels: Area - Documentation 📒

#2975 Backport PR #2972 on branch 1.10.x (Fix double dot)
  docs/conf.py
Labels: Area - Documentation 📒

#2988 Backport PR #2987 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#2989 prep 1.10.1
  docs/release-notes/1.10.1.md
Labels: Development Process 🚀

#2990 Backport PR #2989 on branch 1.10.x (prep 1.10.1)
  docs/release-notes/1.10.1.md
Labels: Development Process 🚀

#2991 start 1.10.2
  docs/release-notes/1.10.2.md
  docs/release-notes/index.md
Labels: Area - Documentation 📒, Development Process 🚀

#2995 Backport PR #2991 on branch 1.10.x (start 1.10.2)
  docs/release-notes/1.10.2.md
  docs/release-notes/index.md
Labels: Area - Documentation 📒, Development Process 🚀

#2994 Fix dev installs
  docs/dev/testing.md
  docs/installation.md
  docs/release-notes/1.10.2.md
  pyproject.toml
  scanpy/testing/_pytest/__init__.py
Labels: Bug 🐛, Development Process 🚀

#2997 Backport PR #2994 on branch 1.10.x (Fix dev installs)
  docs/dev/testing.md
  docs/installation.md
  docs/release-notes/1.10.2.md
  pyproject.toml
  scanpy/testing/_pytest/__init__.py
Labels: Bug 🐛, Development Process 🚀

#2996 Update coverage job
  .azure-pipelines.yml
Labels: Development Process 🚀

#3002 Backport PR #2996 on branch 1.10.x (Update coverage job)
  .azure-pipelines.yml
Labels: Development Process 🚀

#3009 Backport PR #3008 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#2977 Add benchmarks
  .github/workflows/benchmark.yml
  .github/workflows/check-pr.yml
  .github/workflows/publish.yml
  .gitignore
  benchmarks/README.md
  benchmarks/asv.conf.json
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/preprocessing.py
  benchmarks/benchmarks/tools.py
  benchmarks/benchmarks/utils.py
  docs/release-notes/1.10.2.md
  scanpy/_utils/__init__.py
  scanpy/tools/_leiden.py
Labels: benchmark

#3016 Backport PR #2977 on branch 1.10.x (Add benchmarks)
  .github/workflows/benchmark.yml
  .github/workflows/check-pr.yml
  .github/workflows/publish.yml
  .gitignore
  benchmarks/README.md
  benchmarks/asv.conf.json
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/preprocessing.py
  benchmarks/benchmarks/tools.py
  benchmarks/benchmarks/utils.py
  docs/release-notes/1.10.2.md
  scanpy/_utils/__init__.py
  scanpy/tools/_leiden.py
Labels: benchmark

#3018 manually sort bibtex entries ahead of formatting
  docs/references.bib
Labels: Development Process 🚀

#3023 Backport PR #3022 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3015 `sparse_mean_variance_axis` now uses all cores
  benchmarks/asv.conf.json
  benchmarks/benchmarks/preprocessing.py
  benchmarks/benchmarks/utils.py
  docs/release-notes/1.10.2.md
  pyproject.toml
  scanpy/preprocessing/_utils.py
Labels: Area – Performance 🐌, benchmark

#3024 Backport PR #3015 on branch 1.10.x (`sparse_mean_variance_axis` now uses all cores)
  benchmarks/asv.conf.json
  benchmarks/benchmarks/preprocessing.py
  benchmarks/benchmarks/utils.py
  docs/release-notes/1.10.2.md
  pyproject.toml
  scanpy/preprocessing/_utils.py
Labels: Area – Performance 🐌, benchmark

#3034 Relax pytest version restriction
  pyproject.toml
Labels: Development Process 🚀

#3036 Backport PR #3034 on branch 1.10.x (Relax pytest version restriction)
  pyproject.toml
Labels: Development Process 🚀

#3039 Backport PR #3038 on branch 1.10.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  scanpy/external/exporting.py
  scanpy/plotting/_scrublet.py
Labels: Development Process 🚀

#3040 Add triage label to user created issues
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Development Process 🚀
