Repository scverse/scanpy, pull requests merged in 2025-03, with the labels that each got.

#3502 Backport PR #3494 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3510 Update pre-commit
  .pre-commit-config.yaml
  src/scanpy/_compat.py
  src/scanpy/datasets/_datasets.py
  src/scanpy/plotting/_anndata.py
  src/scanpy/preprocessing/_highly_variable_genes.py
  src/scanpy/preprocessing/_pca/_dask_sparse.py
  src/scanpy/preprocessing/_scrublet/core.py
  tests/conftest.py
  tests/test_plotting.py
  tests/test_plotting_utils.py
Labels: Development Process 🚀

#3511 Backport PR #3510 on branch 1.11.x (Update pre-commit)
  .pre-commit-config.yaml
  src/scanpy/_compat.py
  src/scanpy/datasets/_datasets.py
  src/scanpy/plotting/_anndata.py
  src/scanpy/preprocessing/_highly_variable_genes.py
  src/scanpy/preprocessing/_pca/_dask_sparse.py
  src/scanpy/preprocessing/_scrublet/core.py
  tests/conftest.py
  tests/test_plotting.py
  tests/test_plotting_utils.py
Labels: Development Process 🚀

#3516 Fix branch selection
  .github/workflows/ci.yml
Labels: Development Process 🚀, no milestone

#3520 Fix CI (to_zarr and random mask)
  src/testing/scanpy/_helpers/__init__.py
  tests/test_helpers.py
  tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#3521 Backport PR #3520 on branch 1.11.x (Fix CI (to_zarr and random mask))
  src/testing/scanpy/_helpers/__init__.py
  tests/test_helpers.py
  tests/test_preprocessing_distributed.py
Labels: Development Process 🚀

#3524 (chore): clarify `rank_genes_groups` docs
  src/scanpy/tools/_rank_genes_groups.py
Labels: Area - Documentation 📒

#3525 Backport PR #3524 on branch 1.11.x ((chore): clarify `rank_genes_groups` docs)
  src/scanpy/tools/_rank_genes_groups.py
Labels: Area - Documentation 📒

#3530 Backport PR #3526 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3529 Speed up wilcoxon rank-sum test with numba
  benchmarks/benchmarks/tools.py
  docs/release-notes/3529.performance.md
  src/scanpy/experimental/pp/_highly_variable_genes.py
  src/scanpy/tools/_rank_genes_groups.py
Labels: benchmark

#3539 Backport PR #3529 on branch 1.11.x (Speed up wilcoxon rank-sum test with numba)
  benchmarks/benchmarks/tools.py
  docs/release-notes/3529.performance.md
  src/scanpy/experimental/pp/_highly_variable_genes.py
  src/scanpy/tools/_rank_genes_groups.py
Labels: benchmark

#3484 Further .mtx reading improvements
  src/scanpy/datasets/_ebi_expression_atlas.py
  tests/test_datasets.py
Labels: Development Process 🚀

#3540 Backport PR #3484 on branch 1.11.x (Further .mtx reading improvements)
  src/scanpy/datasets/_ebi_expression_atlas.py
  tests/test_datasets.py
Labels: Development Process 🚀

#3546 Backport PR #3545 on branch main ((chore): generate 1.11.1 release notes)
  docs/release-notes/1.11.1.md
  docs/release-notes/3499.bugfix.md
  docs/release-notes/3528.feature.md
  docs/release-notes/3529.performance.md
  docs/release-notes/3534.bugfix.md
Labels: Development Process 🚀, no milestone

#3547 Fix release note header levels
  docs/release-notes/1.10.4.md
  docs/release-notes/1.11.0.md
  docs/release-notes/1.11.1.md
Labels: Area - Documentation 📒, Development Process 🚀

#3548 Backport PR #3547 on branch 1.11.x (Fix release note header levels)
  docs/release-notes/1.10.4.md
  docs/release-notes/1.11.0.md
  docs/release-notes/1.11.1.md
Labels: Area - Documentation 📒, Development Process 🚀

#3549 Update CI and download badges in README
  README.md
Labels: Area - Documentation 📒, Development Process 🚀

#3550 Backport PR #3549 on branch 1.11.x (Update CI and download badges in README)
  README.md
Labels: Area - Documentation 📒, Development Process 🚀
