Repository scverse/scanpy, pull requests merged in 2025-02, with the labels that each got.

#3466 (chore): generate 1.11.0 release notes
  docs/release-notes/1.11.0.md
  docs/release-notes/1.11.0rc1.md
  docs/release-notes/1.11.0rc2.md
  pyproject.toml
Labels: Development Process 🚀, no milestone

#3462 (chore): Simplify BasePlot’s var_groups
  src/scanpy/neighbors/_connectivity.py
  src/scanpy/plotting/_baseplot_class.py
Labels: Development Process 🚀

#3474 Backport PR #3473 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3389 A memory efficient implementation of the .mtx reading function
  src/scanpy/datasets/_ebi_expression_atlas.py
Labels: Area – Performance 🐌

#3482 Backport PR #3481 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3488 (chore): update copyright
  LICENSE
  docs/conf.py
Labels: Development Process 🚀

#3491 Backport PR #3488 on branch 1.11.x ((chore): update copyright)
  LICENSE
  docs/conf.py
Labels: Development Process 🚀
