Repository scverse/scanpy, pull requests merged in 2025-05, with the labels that each got.

#3620 Switch from profimp to tuna for parsing import profiles
  pyproject.toml
  tests/test_performance.py
Labels: Development Process 🚀

#3621 Backport PR #3620 on branch 1.11.x (Switch from profimp to tuna for parsing import profiles)
  pyproject.toml
  tests/test_performance.py
Labels: Development Process 🚀

#3623 Backport PR #3622 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3607 (chore): derive CI matrix from hatch env
  .github/workflows/ci.yml
  .gitignore
  ci/scripts/low-vers.py
  hatch.toml
  pyproject.toml
Labels: Development Process 🚀

#3650 (chore): slightly modernize settings module
  src/scanpy/_settings.py
Labels: Development Process 🚀

#3353 Speed up categorical regressor with numba
  docs/release-notes/3353.performance.md
  src/scanpy/preprocessing/_simple.py
  tests/_data/cat_regressor_for_int_input.npy
  tests/_data/regress_test_small_cat.npy
  tests/test_preprocessing.py
Labels: Area – Performance 🐌, benchmark

#3655 (doc): centralize PCA docs
  docs/conf.py
  docs/references.bib
  docs/release-notes/3655.doc.md
  pyproject.toml
  src/scanpy/preprocessing/_pca/__init__.py
Labels: Area - Documentation 📒

#3660 Backport PR #3655 on branch 1.11.x ((doc): centralize PCA docs)
  docs/conf.py
  docs/references.bib
  docs/release-notes/3655.doc.md
  pyproject.toml
  src/scanpy/preprocessing/_pca/__init__.py
Labels: Area - Documentation 📒
