Repository scverse/scanpy, pull requests merged in 2025-07, with the labels that each got.

#3699 Backport PR #3698 on branch main ((chore): generate 1.11.3 release notes)
  docs/release-notes/1.11.3.md
  docs/release-notes/3667.bugfix.md
  docs/release-notes/3672.doc.md
  docs/release-notes/3685.bugfix.md
  docs/release-notes/3695.bugfix.md
Labels: no milestone

#3705 Backport PR #3692 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  biome.jsonc
  pyproject.toml
  src/scanpy/_settings/verbosity.py
  src/scanpy/_utils/__init__.py
  src/scanpy/experimental/pp/_normalization.py
  src/scanpy/neighbors/__init__.py
  src/scanpy/plotting/_anndata.py
  src/scanpy/plotting/_baseplot_class.py
  src/scanpy/plotting/_utils.py
  src/scanpy/preprocessing/_pca/__init__.py
  tests/test_combat.py
  tests/test_pca.py
  tests/test_scrublet.py
  tests/test_sim.py
Labels: Development Process 🚀

#3711 Backport PR #3710 on branch 1.11.x ((fix): update read_text usage)
  src/scanpy/readwrite.py
Labels: Development Process 🚀

#3690 Include `scipy-stubs` in the optional dev dependencies
  pyproject.toml
Labels: Development Process 🚀

#3715 Backport PR #3712 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3727 Backport PR #3726 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3742 Backport PR #3741 on branch 1.11.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: Development Process 🚀

#3745 (fix): fix igraph on windows
  .github/workflows/ci.yml
  docs/release-notes/3745.bugfix.md
  src/scanpy/_utils/random.py
  tests/_images/heatmap_var_as_dict/expected.png
  tests/notebooks/test_pbmc3k.py
  tests/test_clustering.py
  tests/test_plotting.py
Labels: benchmark
